baseURL = 'https://techva.team/'
languageCode = 'en-us'
title = 'TechVA Team'
theme = "techva-raditian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


[params]

  sections = ["showcase", "who-am-i", "what-can-i-do", "who-do-i-work-with", "about-me", "testimonials", "services", "contact", "newsletter"]
  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "TechVA"
    text2 = "team"

  [params.footer]
      copyright = "© TechVA Team. All rights reserved."
      #[params.footer.radity_logo]
        #x = "img/general/design-and-code-radity.png"
        #_2x = "img/general/design-and-code-radity@2x.png"
        #alt = "Design & Code - Radity"
